(in-package :aoc-problems)

(defun aoc01 ()
  (let ((silver 0)
        (gold nil))
    (let ((l (read-line)))
      (dotimes (i (length l))
        (let* ((v (aref l i))
               (off (if (char= v #\( ) 1 -1)))
          (incf silver off)
          (when (and (null gold) (< silver 0))
            (setf gold (1+ i))))))
      (format *standard-output* "silver: ~A~%" silver)
      (format *standard-output* "gold: ~A~%" gold)))
